package com.iflytek.dep.admin.dao;

import com.iflytek.dep.admin.model.DepEtlJobRecorders;
import com.iflytek.dep.admin.model.dto.DepEtlJobRecordersDto;

import java.util.List;

public interface DepEtlJobRecordersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP_ETL_JOB_RECORDERS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP_ETL_JOB_RECORDERS
     *
     * @mbg.generated
     */
    int insert(DepEtlJobRecorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP_ETL_JOB_RECORDERS
     *
     * @mbg.generated
     */
    int insertSelective(DepEtlJobRecorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP_ETL_JOB_RECORDERS
     *
     * @mbg.generated
     */
    DepEtlJobRecorders selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP_ETL_JOB_RECORDERS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DepEtlJobRecorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEP_ETL_JOB_RECORDERS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DepEtlJobRecorders record);

    int selectStatusNumber(DepEtlJobRecorders record);

    /**
     * 获取所有job执行情况统计
     * @param record
     * @return
     */
    List<DepEtlJobRecorders> getAllListByParam(DepEtlJobRecordersDto record);

    /**
     * 获取所有job执行情况统计
     * @param record
     * @return
     */
    List<DepEtlJobRecorders> getOneJobListByParam(DepEtlJobRecordersDto record);
}