package com.iflytek.dep.admin.model;

import java.math.BigDecimal;
import java.util.Date;

public class DepEtlJobRecorders {
    private String id;

    private String jobId;

    private String jobName;

    private BigDecimal jobType;

    private Date startTime;

    private Date endTime;

    private BigDecimal jobStatus;
    private BigDecimal totalSuccess;
    private BigDecimal totalError;
    private BigDecimal totalNumber;
    private String resultInfo;

    public String getResultInfo() {
        return resultInfo;
    }

    public void setResultInfo(String resultInfo) {
        this.resultInfo = resultInfo;
    }

    public BigDecimal getTotalSuccess() {
        return totalSuccess;
    }

    public void setTotalSuccess(BigDecimal totalSuccess) {
        this.totalSuccess = totalSuccess;
    }

    private BigDecimal rowNumber;

    public BigDecimal getRowNumber() {
        return rowNumber;
    }

    public void setRowNumber(BigDecimal rowNumber) {
        this.rowNumber = rowNumber;
    }

    public BigDecimal getTotalError() {
        return totalError;
    }

    public void setTotalError(BigDecimal totalError) {
        this.totalError = totalError;
    }

    public BigDecimal getTotalNumber() {
        return totalNumber;
    }

    public void setTotalNumber(BigDecimal totalNumber) {
        this.totalNumber = totalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP_ETL_JOB_RECORDERS.ID
     *
     * @return the value of DEP_ETL_JOB_RECORDERS.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP_ETL_JOB_RECORDERS.ID
     *
     * @param id the value for DEP_ETL_JOB_RECORDERS.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP_ETL_JOB_RECORDERS.JOB_ID
     *
     * @return the value of DEP_ETL_JOB_RECORDERS.JOB_ID
     *
     * @mbg.generated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP_ETL_JOB_RECORDERS.JOB_ID
     *
     * @param jobId the value for DEP_ETL_JOB_RECORDERS.JOB_ID
     *
     * @mbg.generated
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP_ETL_JOB_RECORDERS.JOB_NAME
     *
     * @return the value of DEP_ETL_JOB_RECORDERS.JOB_NAME
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP_ETL_JOB_RECORDERS.JOB_NAME
     *
     * @param jobName the value for DEP_ETL_JOB_RECORDERS.JOB_NAME
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP_ETL_JOB_RECORDERS.JOB_TYPE
     *
     * @return the value of DEP_ETL_JOB_RECORDERS.JOB_TYPE
     *
     * @mbg.generated
     */
    public BigDecimal getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP_ETL_JOB_RECORDERS.JOB_TYPE
     *
     * @param jobType the value for DEP_ETL_JOB_RECORDERS.JOB_TYPE
     *
     * @mbg.generated
     */
    public void setJobType(BigDecimal jobType) {
        this.jobType = jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP_ETL_JOB_RECORDERS.START_TIME
     *
     * @return the value of DEP_ETL_JOB_RECORDERS.START_TIME
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP_ETL_JOB_RECORDERS.START_TIME
     *
     * @param startTime the value for DEP_ETL_JOB_RECORDERS.START_TIME
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP_ETL_JOB_RECORDERS.END_TIME
     *
     * @return the value of DEP_ETL_JOB_RECORDERS.END_TIME
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP_ETL_JOB_RECORDERS.END_TIME
     *
     * @param endTime the value for DEP_ETL_JOB_RECORDERS.END_TIME
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEP_ETL_JOB_RECORDERS.JOB_STATUS
     *
     * @return the value of DEP_ETL_JOB_RECORDERS.JOB_STATUS
     *
     * @mbg.generated
     */
    public BigDecimal getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEP_ETL_JOB_RECORDERS.JOB_STATUS
     *
     * @param jobStatus the value for DEP_ETL_JOB_RECORDERS.JOB_STATUS
     *
     * @mbg.generated
     */
    public void setJobStatus(BigDecimal jobStatus) {
        this.jobStatus = jobStatus;
    }
}