package com.iflytek.dep.server.mapper;

import com.iflytek.dep.server.model.SectionStepRecorderInfo;
import com.iflytek.dep.server.model.SectionStepRecorders;

import java.util.List;

public interface SectionStepRecordersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION_STEP_RECORDERS
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION_STEP_RECORDERS
     *
     * @mbg.generated
     */
    int insert(SectionStepRecorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION_STEP_RECORDERS
     *
     * @mbg.generated
     */
    int insertSelective(SectionStepRecorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION_STEP_RECORDERS
     *
     * @mbg.generated
     */
    SectionStepRecorders selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION_STEP_RECORDERS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SectionStepRecorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION_STEP_RECORDERS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SectionStepRecorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SECTION_STEP_RECORDERS
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SectionStepRecorders record);


    /**
     *根据packageID找到该package所执行过的section信息
     * @param packageId
     * @return
     */
    List<SectionStepRecorders> getByPackageId(String packageId);

    /**
     * 获取当前所有未成功执行的PackageID
     * @return
     */
    List<SectionStepRecorderInfo> getAllUnSuccessPakcage();


    /**
     *  获取当前所有的子包
     * @param packageId
     * @return
     */
    List<String> listPackageSub(String packageId);

    List<SectionStepRecorders> getNeedEtlInfoRecords();

    int deleteFailSectionStepRecorders(String packageId);
}