-- Add/modify columns
--给抽取记录表添加包名字段（不包含扩展名）
ALTER TABLE DEP_ETL_JOB_RECORDERS ADD(PACKAGE_ID  VARCHAR2(220) default null)  ;
comment on column DEP_ETL_JOB_RECORDERS.PACKAGE_ID
  is '数据主包名，不包含扩展名';

--通知工作流记录表
DROP TABLE "ETL_TO_WORKFLOW_RECORDERS";
CREATE TABLE "ETL_TO_WORKFLOW_RECORDERS" (
"ID" VARCHAR2(150 BYTE) NOT NULL ,
"JOB_NAME" VARCHAR2(150 BYTE) NOT NULL ,
"JOB_PARAM" CLOB DEFAULT NULL  NULL ,
"START_TIME" DATE NOT NULL ,
"END_TIME" DATE NULL ,
"JOB_STATUS" NUMBER NOT NULL ,
"JOB_RESULT_INFO" CLOB NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "ETL_TO_WORKFLOW_RECORDERS"."ID" IS '主键';
COMMENT ON COLUMN "ETL_TO_WORKFLOW_RECORDERS"."JOB_NAME" IS 'JOB名称';
COMMENT ON COLUMN "ETL_TO_WORKFLOW_RECORDERS"."JOB_PARAM" IS 'JOB参数';
COMMENT ON COLUMN "ETL_TO_WORKFLOW_RECORDERS"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "ETL_TO_WORKFLOW_RECORDERS"."END_TIME" IS '结束时间';
COMMENT ON COLUMN "ETL_TO_WORKFLOW_RECORDERS"."JOB_STATUS" IS 'job状态(0-RUNNING,1-DONE,2-FAILED)';
COMMENT ON COLUMN "ETL_TO_WORKFLOW_RECORDERS"."JOB_RESULT_INFO" IS 'JOB执行结果信息';
  --给抽取记录表添加包名字段（不包含扩展名）
ALTER TABLE ETL_TO_WORKFLOW_RECORDERS ADD(PACKAGE_ID  VARCHAR2(220) default null)  ;
comment on column ETL_TO_WORKFLOW_RECORDERS.PACKAGE_ID
  is '数据主包名，不包含扩展名';
  
--是否异常流转视图  根据NODE_ID找APP_ID
CREATE OR REPLACE VIEW  V_IS_UNUSUAL_TRANSFER AS
SELECT p.PACKAGE_ID AS PKG_ID,
	   n.app_id as APP_ID_TO,
	   CASE WHEN p.global_state_dm = '00' THEN 1 ELSE 0
	   END AS IS_UNUSUAL_TRANSFER
  FROM package_global_state p
  left join node_app n on n.node_id=p.to_node_id
   WITH READ ONLY;
  COMMIT;