package com.iflytek.dep.server.model;

import java.math.BigDecimal;
import java.util.Date;

public class SectionStepRecorders {
    private String id;

    private String sectionName;

    private BigDecimal doactResult;

    private String packageId;

    private BigDecimal totalSectionNumber;

    private Date createTime;

    private String sectionParam;

	private BigDecimal direction;

	public BigDecimal getDirection() {
		return direction;
	}

	public void setDirection(BigDecimal direction) {
		this.direction = direction;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION_STEP_RECORDERS.ID
     *
     * @return the value of SECTION_STEP_RECORDERS.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION_STEP_RECORDERS.ID
     *
     * @param id the value for SECTION_STEP_RECORDERS.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION_STEP_RECORDERS.SECTION_NAME
     *
     * @return the value of SECTION_STEP_RECORDERS.SECTION_NAME
     *
     * @mbg.generated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION_STEP_RECORDERS.SECTION_NAME
     *
     * @param sectionName the value for SECTION_STEP_RECORDERS.SECTION_NAME
     *
     * @mbg.generated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION_STEP_RECORDERS.DOACT_RESULT
     *
     * @return the value of SECTION_STEP_RECORDERS.DOACT_RESULT
     *
     * @mbg.generated
     */
    public BigDecimal getDoactResult() {
        return doactResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION_STEP_RECORDERS.DOACT_RESULT
     *
     * @param doactResult the value for SECTION_STEP_RECORDERS.DOACT_RESULT
     *
     * @mbg.generated
     */
    public void setDoactResult(BigDecimal doactResult) {
        this.doactResult = doactResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION_STEP_RECORDERS.PACKAGE_ID
     *
     * @return the value of SECTION_STEP_RECORDERS.PACKAGE_ID
     *
     * @mbg.generated
     */
    public String getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION_STEP_RECORDERS.PACKAGE_ID
     *
     * @param packageId the value for SECTION_STEP_RECORDERS.PACKAGE_ID
     *
     * @mbg.generated
     */
    public void setPackageId(String packageId) {
        this.packageId = packageId == null ? null : packageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION_STEP_RECORDERS.TOTAL_SECTION_NUMBER
     *
     * @return the value of SECTION_STEP_RECORDERS.TOTAL_SECTION_NUMBER
     *
     * @mbg.generated
     */
    public BigDecimal getTotalSectionNumber() {
        return totalSectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION_STEP_RECORDERS.TOTAL_SECTION_NUMBER
     *
     * @param totalSectionNumber the value for SECTION_STEP_RECORDERS.TOTAL_SECTION_NUMBER
     *
     * @mbg.generated
     */
    public void setTotalSectionNumber(BigDecimal totalSectionNumber) {
        this.totalSectionNumber = totalSectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION_STEP_RECORDERS.CREATE_TIME
     *
     * @return the value of SECTION_STEP_RECORDERS.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION_STEP_RECORDERS.CREATE_TIME
     *
     * @param createTime the value for SECTION_STEP_RECORDERS.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SECTION_STEP_RECORDERS.SECTION_PARAM
     *
     * @return the value of SECTION_STEP_RECORDERS.SECTION_PARAM
     *
     * @mbg.generated
     */
    public String getSectionParam() {
        return sectionParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SECTION_STEP_RECORDERS.SECTION_PARAM
     *
     * @param sectionParam the value for SECTION_STEP_RECORDERS.SECTION_PARAM
     *
     * @mbg.generated
     */
    public void setSectionParam(String sectionParam) {
        this.sectionParam = sectionParam == null ? null : sectionParam.trim();
    }
}